services:
  postgres:
    container_name: postgres_stack_kata
    image: postgres
    env_file: .env.example
    volumes:
      - ./database/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
