version: "3.9"
services:
  postgres:
    container_name: postgres_stack_kata
    image: postgres:latest
    environment:
      POSTGRES_DB: "stack_kata_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    volumes:
      - ./database/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"